version: "3.9"
services:
  manager:
    build:
      context: .
      dockerfile: ManagerDockerfile
    environment:
      DOMAIN: localhost.local
      TABLE_NAME: only
      ENVIRONMENT: "local"
    ports:
      - "8000:8000"
  dynamodb:
    image: amazon/dynamodb-local
    ports:
    - "8001:8000"
