version: "3.9"
services:
  manager:
    build:
      context: .
      dockerfile: ManagerDockerfile
    command: ["/opt/"]
    environment:
      FORWARDER_EMAIL_PREFIX: forwarder
      DOMAIN: localhost:8000
      TABLE_NAME: LocalTable
      ENVIRONMENT: local
    volumes:
      - "/Users/halprin/Desktop/:/opt/"
    ports:
      - "8000:8000"
    depends_on: [dynamodb]
  forwarder:
    build:
      context: .
      dockerfile: ForwarderDockerfile
    command: ["/opt/"]
    environment:
      FORWARDER_EMAIL_PREFIX: forwarder
      DOMAIN: localhost:8000
      TABLE_NAME: LocalTable
      ENVIRONMENT: local
    volumes:
      - "/Users/halprin/Desktop/:/opt/"
    depends_on: [dynamodb]
  dynamodb:
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
    - "8001:8000"
  dynamodbAdmin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8002:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on: [dynamodb]
