version: "3.9"
services:
  manager:
    build:
      context: .
      dockerfile: ManagerDockerfile
    command: ["/opt/"]
    environment:
      FORWARDER_EMAIL_PREFIX: forwarder
      DOMAIN: localhost.local
      TABLE_NAME: LocalTable
      ENVIRONMENT: local
    volumes:
      - "/Users/halprin/Desktop/:/opt/"
    ports:
      - "8000:8000"
    depends_on: [dynamodb]
  forwarder:
    build:
      context: .
      dockerfile: ForwarderDockerfile
    command: ["/opt/"]
    environment:
      FORWARDER_EMAIL_PREFIX: forwarder
      DOMAIN: localhost.local
      TABLE_NAME: LocalTable
      ENVIRONMENT: local
    volumes:
      - "/Users/halprin/Desktop/:/opt/"
    depends_on: [dynamodb]
  dynamodb:
    image: amazon/dynamodb-local
    ports:
    - "8001:8000"
