name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:

    - name: Set-up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Compile
      run: make compileForLinux

    - name: Test
      run: make test

    - name: Terraform has correct formatting
      run: terraform fmt -check -recursive ./iac/

    - name: Build Forwarder Docker image
      run: docker build -f ForwarderDockerfile .

    - name: Build Manager Docker image
      run: docker build -f ManagerDockerfile .
