name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set-up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        pushd ./forwarder/
        go get -v -t -d ./
        popd
        pushd ./src/
        go get -v -t -d ./
        popd
        
    - name: Test Forwarder
      run: |
        cd ./forwarder/
        go test -v ./...

    - name: Build Forwarder
      run: |
        cd ./forwarder/
        go build -v ./

    - name: Test Manager
      run: |
        cd ./src/
        go test -v ./...

    - name: Build Manager
      run: |
        cd ./src/
        go build -v ./cmd/manager/

    - name: Terraform has correct formatting
      run: terraform fmt -check -recursive ./iac/
